"""Remove cost add metrics to UsageLog

Revision ID: c17697ed16d4
Revises: d1bb97177fed
Create Date: 2026-03-29 00:55:55.063625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c17697ed16d4'
down_revision: Union[str, None] = 'd1bb97177fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_table('alerts')
    op.alter_column('model_configs', 'model_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Type: llm, asr, tts',
               existing_nullable=False)
    op.alter_column('model_configs', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Model name: qwen3-tts-instruct-flash',
               existing_nullable=False)
    op.alter_column('model_configs', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Provider: dashscope, openai',
               existing_nullable=False)
    op.alter_column('model_configs', 'api_key_encrypted',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Encrypted API key',
               existing_nullable=True)
    op.alter_column('model_configs', 'config',
               existing_type=mysql.JSON(),
               comment='Model-specific config',
               existing_nullable=False)
    op.alter_column('model_configs', 'price_per_1k_input_tokens',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               comment='Price per 1K input tokens',
               existing_nullable=False,
               existing_server_default=sa.text("'0.000000'"))
    op.alter_column('model_configs', 'price_per_1k_output_tokens',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               comment='Price per 1K output tokens',
               existing_nullable=False,
               existing_server_default=sa.text("'0.000000'"))
    op.alter_column('model_configs', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Default model for type and terminal',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('model_configs', 'terminal_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Terminal: all, web, ios, android, miniprogram',
               existing_nullable=False,
               existing_server_default=sa.text("'all'"))
    op.add_column('usage_logs', sa.Column('provider', sa.String(length=50), nullable=True, comment='供应商：aliyun/openai/anthropic'))
    op.add_column('usage_logs', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False, comment='总 Token 数'))
    op.add_column('usage_logs', sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False, comment='总延迟'))
    op.add_column('usage_logs', sa.Column('asr_latency_ms', sa.Integer(), nullable=True, comment='ASR 延迟'))
    op.add_column('usage_logs', sa.Column('llm_latency_ms', sa.Integer(), nullable=True, comment='LLM 延迟'))
    op.add_column('usage_logs', sa.Column('tts_latency_ms', sa.Integer(), nullable=True, comment='TTS 延迟'))
    op.add_column('usage_logs', sa.Column('request_size_bytes', sa.Integer(), nullable=True, comment='请求大小'))
    op.add_column('usage_logs', sa.Column('response_size_bytes', sa.Integer(), nullable=True, comment='响应大小'))
    op.add_column('usage_logs', sa.Column('success', sa.Boolean(), nullable=False, comment='是否成功'))
    op.add_column('usage_logs', sa.Column('error_code', sa.String(length=50), nullable=True, comment='错误代码'))
    op.add_column('usage_logs', sa.Column('error_message', sa.String(length=500), nullable=True, comment='错误信息'))
    op.alter_column('usage_logs', 'model_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='模型类型：llm/asr/tts/vision',
               existing_nullable=False)
    op.alter_column('usage_logs', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='模型名称',
               existing_nullable=False)
    op.alter_column('usage_logs', 'input_tokens',
               existing_type=mysql.INTEGER(),
               comment='输入 Token 数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('usage_logs', 'output_tokens',
               existing_type=mysql.INTEGER(),
               comment='输出 Token 数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('usage_logs', 'terminal_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='终端类型：web/ios/android',
               existing_nullable=False,
               existing_server_default=sa.text("'web'"))
    op.alter_column('usage_logs', 'extra_data',
               existing_type=mysql.JSON(),
               comment='额外数据（JSON）',
               existing_nullable=False)
    op.create_index('idx_model_type_created', 'usage_logs', ['model_type', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'usage_logs', ['user_id', 'created_at'], unique=False)
    op.drop_column('usage_logs', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('cost', mysql.DECIMAL(precision=10, scale=6), server_default=sa.text("'0.000000'"), nullable=False))
    op.drop_index('idx_user_created', table_name='usage_logs')
    op.drop_index('idx_model_type_created', table_name='usage_logs')
    op.alter_column('usage_logs', 'extra_data',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='额外数据（JSON）',
               existing_nullable=False)
    op.alter_column('usage_logs', 'terminal_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='终端类型：web/ios/android',
               existing_nullable=False,
               existing_server_default=sa.text("'web'"))
    op.alter_column('usage_logs', 'output_tokens',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='输出 Token 数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('usage_logs', 'input_tokens',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='输入 Token 数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('usage_logs', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='模型名称',
               existing_nullable=False)
    op.alter_column('usage_logs', 'model_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='模型类型：llm/asr/tts/vision',
               existing_nullable=False)
    op.drop_column('usage_logs', 'error_message')
    op.drop_column('usage_logs', 'error_code')
    op.drop_column('usage_logs', 'success')
    op.drop_column('usage_logs', 'response_size_bytes')
    op.drop_column('usage_logs', 'request_size_bytes')
    op.drop_column('usage_logs', 'tts_latency_ms')
    op.drop_column('usage_logs', 'llm_latency_ms')
    op.drop_column('usage_logs', 'asr_latency_ms')
    op.drop_column('usage_logs', 'latency_ms')
    op.drop_column('usage_logs', 'total_tokens')
    op.drop_column('usage_logs', 'provider')
    op.alter_column('model_configs', 'terminal_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Terminal: all, web, ios, android, miniprogram',
               existing_nullable=False,
               existing_server_default=sa.text("'all'"))
    op.alter_column('model_configs', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Default model for type and terminal',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('model_configs', 'price_per_1k_output_tokens',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               comment=None,
               existing_comment='Price per 1K output tokens',
               existing_nullable=False,
               existing_server_default=sa.text("'0.000000'"))
    op.alter_column('model_configs', 'price_per_1k_input_tokens',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               comment=None,
               existing_comment='Price per 1K input tokens',
               existing_nullable=False,
               existing_server_default=sa.text("'0.000000'"))
    op.alter_column('model_configs', 'config',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Model-specific config',
               existing_nullable=False)
    op.alter_column('model_configs', 'api_key_encrypted',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Encrypted API key',
               existing_nullable=True)
    op.alter_column('model_configs', 'provider',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Provider: dashscope, openai',
               existing_nullable=False)
    op.alter_column('model_configs', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Model name: qwen3-tts-instruct-flash',
               existing_nullable=False)
    op.alter_column('model_configs', 'model_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Type: llm, asr, tts',
               existing_nullable=False)
    op.create_table('alerts',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('level', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("'warning'"), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('message', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000), nullable=False),
    sa.Column('metadata', mysql.JSON(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    # ### end Alembic commands ###
