"""add role and model_configs

Revision ID: 54cb82f10440
Revises: c4a8b9c0e2d1
Create Date: 2026-03-26 18:32:35.785764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54cb82f10440'
down_revision: Union[str, None] = 'c4a8b9c0e2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'metadata',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('model_configs', 'model_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='Type: llm, asr, tts',
               existing_nullable=False)
    op.alter_column('model_configs', 'model_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='Model name: qwen3-tts-instruct-flash',
               existing_nullable=False)
    op.alter_column('model_configs', 'provider',
               existing_type=mysql.VARCHAR(length=50),
               comment='Provider: dashscope, openai',
               existing_nullable=False)
    op.alter_column('model_configs', 'api_key_encrypted',
               existing_type=mysql.TEXT(),
               comment='Encrypted API key',
               existing_nullable=True)
    op.alter_column('model_configs', 'config',
               existing_type=mysql.JSON(),
               nullable=False,
               comment='Model-specific config')
    op.alter_column('model_configs', 'price_per_1k_input_tokens',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               comment='Price per 1K input tokens',
               existing_nullable=False,
               existing_server_default=sa.text("'0.000000'"))
    op.alter_column('model_configs', 'price_per_1k_output_tokens',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               comment='Price per 1K output tokens',
               existing_nullable=False,
               existing_server_default=sa.text("'0.000000'"))
    op.alter_column('model_configs', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Default model for type and terminal',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('model_configs', 'terminal_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='Terminal: all, web, ios, android, miniprogram',
               existing_nullable=False,
               existing_server_default=sa.text("'all'"))
    op.alter_column('model_configs', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('model_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('model_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_model_type'), table_name='model_configs')
    op.create_index(op.f('ix_model_configs_model_type'), 'model_configs', ['model_type'], unique=False)
    op.alter_column('request_logs', 'extra_data',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_index(op.f('ix_request_logs_status_code'), table_name='request_logs')
    op.create_index(op.f('ix_request_logs_user_id'), 'request_logs', ['user_id'], unique=False)
    op.drop_index(op.f('key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.alter_column('terminals', 'config_overrides',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('terminals', 'feature_flags',
               existing_type=mysql.JSON(),
               nullable=False)
    op.drop_index(op.f('type'), table_name='terminals')
    op.drop_index(op.f('ix_terminals_type'), table_name='terminals')
    op.create_index(op.f('ix_terminals_type'), 'terminals', ['type'], unique=True)
    op.alter_column('usage_logs', 'extra_data',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_logs', 'extra_data',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_index(op.f('ix_terminals_type'), table_name='terminals')
    op.create_index(op.f('ix_terminals_type'), 'terminals', ['type'], unique=False)
    op.create_index(op.f('type'), 'terminals', ['type'], unique=True)
    op.alter_column('terminals', 'feature_flags',
               existing_type=mysql.JSON(),
               nullable=True)
    op.alter_column('terminals', 'config_overrides',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_index(op.f('key'), 'system_settings', ['key'], unique=True)
    op.drop_index(op.f('ix_request_logs_user_id'), table_name='request_logs')
    op.create_index(op.f('ix_request_logs_status_code'), 'request_logs', ['status_code'], unique=False)
    op.alter_column('request_logs', 'extra_data',
               existing_type=mysql.JSON(),
               nullable=True)
    op.drop_index(op.f('ix_model_configs_model_type'), table_name='model_configs')
    op.create_index(op.f('idx_model_type'), 'model_configs', ['model_type'], unique=False)
    op.alter_column('model_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('model_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('model_configs', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('model_configs', 'terminal_type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Terminal: all, web, ios, android, miniprogram',
               existing_nullable=False,
               existing_server_default=sa.text("'all'"))
    op.alter_column('model_configs', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Default model for type and terminal',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('model_configs', 'price_per_1k_output_tokens',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               comment=None,
               existing_comment='Price per 1K output tokens',
               existing_nullable=False,
               existing_server_default=sa.text("'0.000000'"))
    op.alter_column('model_configs', 'price_per_1k_input_tokens',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               comment=None,
               existing_comment='Price per 1K input tokens',
               existing_nullable=False,
               existing_server_default=sa.text("'0.000000'"))
    op.alter_column('model_configs', 'config',
               existing_type=mysql.JSON(),
               nullable=True,
               comment=None,
               existing_comment='Model-specific config')
    op.alter_column('model_configs', 'api_key_encrypted',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Encrypted API key',
               existing_nullable=True)
    op.alter_column('model_configs', 'provider',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Provider: dashscope, openai',
               existing_nullable=False)
    op.alter_column('model_configs', 'model_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Model name: qwen3-tts-instruct-flash',
               existing_nullable=False)
    op.alter_column('model_configs', 'model_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Type: llm, asr, tts',
               existing_nullable=False)
    op.alter_column('alerts', 'metadata',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###
